spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secur-db
    username: mus
    password: mus
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        hbm2ddl:
          auto: validate
    show-sql: true
jwt:
  secret: secret
  lifetime: 30m